Transform: AWS::Serverless-2016-10-31
Resources:
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
        BlockPublicPolicy: FALSE
        IgnorePublicAcls: FALSE
        RestrictPublicBuckets: FALSE

  ResumeBucketAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "ResumeBucket"
                  - "/resume.pdf"
            Principal: "*"

  EmailApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: REGIONAL
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  EmailApiAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt EmailApiCloudWatchRole.Arn

  EmailApiCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref EmailApi
      Runtime: python3.7
      Handler: index.handler
      Role: !GetAtt EmailFunctionRole.Arn
      InlineCode:
        !Join
          - "\n"
          - - "import json"
            - "import boto3"
            - "client = boto3.client('sns')"
            - "def handler(event, __):"
            - "  print(event['body'])"
            - "  body = json.loads(event['body'])"
            - "  print(body)"
            - "  statusCode=200"
            - "  try:"
            - "    client.publish("
            - !Sub 
              - "      TopicArn=\"${SnsTopic}\","
              - { SnsTopic: !Ref EmailTopic }
            - "      Message=body['message'],"
            - "      Subject=\"Email from Resume Website: \"+body['name']+\" - \"+body['email']"
            - "    )"
            - "  except:"
            - "    statusCode=500"
            - "  return {"
            - "    \"statusCode\": statusCode,"
            - "     \"headers\": {"
            # - "         \"Access-Control-Allow-Headers\": \"Content-Type\","
            - "         \"Access-Control-Allow-Origin\": \"*\","
            - "         \"Access-Control-Allow-Methods\": \"OPTIONS,POST,GET\""
            - "     },"
            - "    \"body\": \"Hello from Lambda!\""
            - "  }"

  EmailFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  EmailFunctionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaPolicy
      Roles:
        - !Ref EmailFunctionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "sns:Publish"
            Resource: !Ref EmailTopic

  EmailTopic:
    Type: AWS::SNS::Topic

  EmailTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref EmailTopic
      Protocol: email
      Endpoint: andrew.pvh.ha@gmail.com